# Generated by Django 5.0.1 on 2024-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Breakkfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Beverages'), (5, 'Anytime')], verbose_name='category'),
        ),
    ]
