# Generated by Django 5.0.1 on 2024-02-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_alter_menu_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_list',
            field=models.IntegerField(choices=[(1, 'Appetizers'), (2, 'Soups'), (3, 'Bread and Rice'), (4, 'Curries'), (5, 'Tandoori Specialties'), (6, 'Vegetarian Main Courses'), (7, 'Non-Vegetarian Main Courses'), (8, 'Desserts'), (9, 'Beverages')], default=1, verbose_name='Menu List'),
        ),
    ]
